// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXYDkBwTkH93DOLCGqndtTC5us4fnlzU',
    appId: '1:995507730731:web:1d8d0e5e8b8aca94852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    authDomain: 'servicemanagement-saas.firebaseapp.com',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    measurementId: 'G-0KPSYE9DP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgK8yrD0fjUuHTULzbdVrMfkqRDdl9hFU',
    appId: '1:995507730731:android:cf73a6ce82fb5d60852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUDXEfVhRNPj10jqPReeNz4Mc63edSAs',
    appId: '1:995507730731:ios:1696d0ddfb51d7a2852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    iosBundleId: 'com.unisapphire.techserve.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXYDkBwTkH93DOLCGqndtTC5us4fnlzU',
    appId: '1:995507730731:web:d85e6362b2787ed3852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    authDomain: 'servicemanagement-saas.firebaseapp.com',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    measurementId: 'G-NGY94KDH3L',
  );
}
